apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
 name: go-proxy-monitor
 namespace: default
 labels:
   release: obs-mesh
spec:
  selector:
    matchLabels: 
      proxy-instance: edge-gateway
  endpoints:
  - port: metrics-scrape
    interval: 10s
    path: /metrics