apiVersion: networking.krish.platform/v1alpha1
kind: ProxyService
metadata:
  name: edge-gateway
  namespace: default
  labels:
    app.kubernetes.io/name: go-proxy-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 2
  listenPort: 8080
  rateLimit: 25
  upstreams:
    - "payment-svc-stable:8001"
    - "payment-svc-canary:8001"